name: Deploy to the Edge
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
    deploy:
      runs-on: ubuntu-latest
      timeout-minutes: 60
      steps:
        - uses: actions/checkout@v2
        - name: Publish
          uses: cloudflare/wrangler-action@1.2.0
          with:
            apiToken: ${{ secrets.CF_API_TOKEN }}
          env:
            accountId: f2d3b5a3c7632ca474f06db4717b00b2
